// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "directory": string;
      "templates.directory": string;
      "template.default": string;
      "templates.include_empty_placeholders": boolean;
      "filename.template": string;
      "attach_to_zotero": boolean;
      "create_notes_file": boolean;
      "file_conf": string;
      "files.zotero.metadata.prefix": string;
      "files.zotero.metadata.suffix": string;
      "files.zotero.note.prefix": string;
      "files.zotero.note.suffix": string;
      "files.mdnotes.hub.prefix": string;
      "files.mdnotes.hub.suffix": string;
      "frontmatter.fields": string;
      "placeholder.title": string;
      "placeholder.abstractNote": string;
      "placeholder.author": string;
      "placeholder.collections": string;
      "placeholder.related": string;
      "placeholder.notes": string;
      "placeholder.tags": string;
      "placeholder.url": string;
      "placeholder.DOI": string;
      "placeholder.cloudLibrary": string;
      "placeholder.localLibrary": string;
      "placeholder.noteContent": string;
      "html.strong": boolean;
      "html.em": boolean;
      "html.strikethrough": boolean;
      "html.underline": boolean;
      "html.bullet": boolean;
      "frontmatter.enabled": boolean;
      "frontmatter.format": string;
      "obsidian.attach_obsidian_uri": boolean;
      "obsidian.block_ids": boolean;
      "obsidian.vault": string;
      "obsidian.dir": string;
    };
  }
}
